#!/usr/bin/env python3
"""Register directional drawn paws in 2D, extending the side-cycle planting workflow.
Inputs are regenerated by cut-directions.py. Outputs remain eight drawn sprite frames.
A soft leg warp pivots below the torso; alternating fore/hind stance chains retain
one world contact while the body advances. Padding is recorded for the runtime anchor.
"""
import json
from pathlib import Path
import numpy as np
from scipy import ndimage as nd
from PIL import Image
ROOT=Path(__file__).resolve().parents[2]
STRIDES=dict.fromkeys(['orange','black','grey','calico','siamese'],.5)
metadata={};reports={}
for coat,stride in STRIDES.items():
 metadata['cats/'+coat]={}
 for view in ['f','b']:
  folder=ROOT/f'scenes/art/sprites/cats/{coat}/cycle'
  frames=[np.array(Image.open(folder/f'walk-{view}-{i}.png')).astype(float) for i in range(1,9)]
  h=frames[0].shape[0];ms=[]
  for a in frames:
   al=a[:,:,3]>127;ys=np.where(al.any(1))[0];top,bot=ys[0],ys[-1]
   cx=np.where(al[round(top+(bot-top)*.3):round(top+(bot-top)*.65)+1])[1].mean()
   ms.append((top,bot,cx))
  H=float(np.median([b-t+1 for t,b,c in ms]));cs=np.array([m[2] for m in ms])
  for _ in range(2):cs=(np.roll(cs,1)+2*cs+np.roll(cs,-1))/4
  # Lowest opaque lobe in each limb group. The raised far paw stays in the source art.
  paws=[]
  for a,(_,_,cx) in zip(frames,ms):
   al=a[:,:,3]>127;yy,xx=np.mgrid[:a.shape[0],:a.shape[1]];p=[]
   for side in [-1,1]:
    split=cx-.12*H if view=='f' else cx
    mask=al&((xx<split) if side<0 else (xx>=split));ys=np.where(mask)[0];b=ys.max()
    foot=mask&(yy>=b-max(2,H*.015));p.append([xx[foot].mean(),yy[foot].mean()])
   paws.append(p)
  paws=np.array(paws);rel=paws.copy();rel[:,:,0]-=cs[:,None]
  direction=np.array([1,1 if view=='f' else -1])/np.sqrt(2)
  step=direction*stride*H/8
  offsets=np.zeros((8,2,2));chains=[]
  # Fore and hind contacts alternate every quarter stride. Each group hands over
  # to the opposite leg at half-stride; don't enforce a contact across that hand-off.
  for group,contact in [(0,2),(1,0)]:
   for start in [contact,(contact+4)%8]:
    inds=[(start+j)%8 for j in range(4)]
    world=np.array([rel[i,group]+j*step for j,i in enumerate(inds)])
    target=world.mean(0)
    for j,i in enumerate(inds):offsets[i,group]=target-world[j]
    chains.append((group,inds))
  # Bound art corrections; huge corrections signal a wrong lobe detection.
  if np.max(np.linalg.norm(offsets,axis=2))>H*.34:raise ValueError((coat,view,'excessive paw correction'))
  pad=int(np.ceil(H*.36));metadata['cats/'+coat]['walk-'+view]={'height':H,'pad':pad,'stride':stride,'centers':[round(m[2],6) for m in ms]}
  residuals=[]
  for i,a in enumerate(frames):
   ih,iw,_=a.shape;yy,xx=np.mgrid[-pad:ih+pad,-pad:iw+pad].astype(float)
   # Blend limb groups through the torso, not across the separated paw tips.
   def displacement(x,y):
    wf=np.clip((x-(paws[i,0,0]+6))/max(1,paws[i,1,0]-paws[i,0,0]-12),0,1)
    wf=wf*wf*(3-2*wf)
    out=np.zeros(x.shape+(2,))
    for gi,w in [(0,1-wf),(1,wf)]:
     r=np.clip((y-(paws[i,gi,1]-.40*H))/(.40*H-8),0,1)
     r=r*r*(3-2*r)
     out+= (w*r)[...,None]*offsets[i,gi]
    return out
   # Invert the smooth forward warp before sampling premultiplied source pixels.
   sx,sy=xx.copy(),yy.copy()
   for _ in range(40):
    d=displacement(sx,sy);sx+=(xx-sx-d[:,:,0])*.35;sy+=(yy-sy-d[:,:,1])*.35
   premul=a.copy();premul[:,:,:3]*=premul[:,:,3:4]/255
   warped=np.stack([nd.map_coordinates(premul[:,:,c],[sy,sx],order=1,mode='constant',cval=0) for c in range(4)],-1)
   # Preserve the drawn paw silhouettes rigidly. An inverse deformation can pick
   # the wrong branch where two legs overlap; restoring the local paw patch avoids
   # torn toes while leaving the leg-to-body warp smooth.
   for gi in range(2):
    shift=offsets[i,gi];dest=paws[i,gi]+shift
    radius=np.hypot(xx-dest[0],yy-dest[1])
    mix=np.clip((.10*H-radius)/(.05*H),0,1);mix=mix*mix*(3-2*mix)
    rigid=np.stack([nd.map_coordinates(premul[:,:,c],[yy-shift[1],xx-shift[0]],order=1,mode='constant',cval=0) for c in range(4)],-1)
    warped=warped*(1-mix[:,:,None])+rigid*mix[:,:,None]
   alpha=warped[:,:,3:4];warped[:,:,:3]=warped[:,:,:3]*255/np.maximum(alpha,1e-6)
   clean=np.clip(warped,0,255).astype('uint8')
   labels,_=nd.label(clean[:,:,3]>8);counts=np.bincount(labels.ravel());counts[0]=0
   keep=nd.binary_dilation(labels==counts.argmax(),iterations=1)
   clean[:,:,3]=np.where(keep,clean[:,:,3],0)
   Image.fromarray(clean).save(folder/f'walk-{view}-{i+1}.png')
   # Measured forward-warp displacement at the actual input paw landmarks.
   residuals.append(np.array([displacement(np.array(p[0]),np.array(p[1])) for p in paws[i]]))
  corrected=rel+np.array(residuals);slips=[]
  for gi,inds in chains:
   pts=np.array([corrected[i,gi]+j*step for j,i in enumerate(inds)])
   slips.extend(np.linalg.norm(np.diff(pts,axis=0),axis=1).tolist())
  report={'height':H,'stride':stride,'direction':direction.tolist(),'step':step.tolist(),'paw_landmarks':paws.tolist(),
   'offsets':offsets.tolist(),'stance_chains':chains,'max_contact_slip_px':max(slips),'mean_contact_slip_px':float(np.mean(slips))}
  reports[coat+'-'+view]=report
  print(coat,view,'contact slip',round(max(slips),2),'source pixels',flush=True)
(ROOT/'art-src/cycles/directions-layout.json').write_text(json.dumps(metadata,indent=2)+'\n')
(ROOT/'art-src/cycles/directions-plant-qa.json').write_text(json.dumps(reports,indent=2)+'\n')
