#!/usr/bin/env python3
"""Package atlas metadata as synchronous JS for WKWebView file:// origins."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[2]
data={}
for coat in ['orange','black','grey','calico','siamese']:
 p=ROOT/f'scenes/art/sprites/cats/{coat}/atlas/manifest.json'
 if not p.exists():continue
 clips=json.loads(p.read_text());unit=78/sorted(r[3] for r in clips['walk-side']['frames'])[4]
 # Measured planted paw sweep, in scene units per full cycle (see registration notes).
 for key,c in clips.items():
  if key.startswith(('walk-','run-')):c['stride']=c.get('stride') or ({'side':36,'near':42,'toward':35,'far':36,'away':37}[key.split('-')[1]] if key.startswith('walk') else 110)
 data[coat]={'unit':round(unit,6),'clips':clips}
(ROOT/'scenes/cat-atlas.js').write_text('/* Generated by tools/cats-qa/manifest.py. Explicit source rect and foot anchors. */\nLW.CAT_ATLAS='+json.dumps(data,separators=(',',':'))+';\n')
