name = "wallpap-play-counts"
main = "worker.mjs"
compatibility_date = "2026-10-04"
workers_dev = false
routes = [{ pattern = "wallpap.live/counts", zone_name = "wallpap.live" }]

[observability]
enabled = false

[[d1_databases]]
binding = "DB"
database_name = "wallpap-play-counts"
database_id = "cbfd252d-156a-475b-8b0b-4c3e6c1f881c"
