/* The trusted Play shell. Cards never receive a native bridge or an origin. */
(()=>{'use strict';
const base=new URL('.',document.currentScript.src),pending=new Map();let sequence=0,root,frame,current,config={},closing=false,epoch=0,category='Puzzles',previousFocus=true,dayTimer;
const allowedLinks=new Set(),themeQuery=matchMedia('(prefers-color-scheme: dark)');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svg=(kind)=>`<svg viewBox="0 0 20 20" aria-hidden="true">${kind==='news'?'<path d="M3 3h14v14H3zM6 6h8M6 10h8M6 14h5"/>':kind==='back'?'<path d="m12 4-6 6 6 6"/>':kind==='close'?'<path d="m5 5 10 10M15 5 5 10"/>':'<rect x="3" y="3" width="14" height="14" rx="3"/><path d="M3 10h14M10 3v14"/>'}</svg>`;
const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('play.css',base);document.head.append(css);
function script(name){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL(name,base);s.onload=resolve;s.onerror=()=>reject(Error('Play content could not load'));document.head.append(s);});}
const loaded=Promise.all([script('core.js'),script('catalog.js'),script('config.js')]);
function theme(){return {mode:config.theme|| (themeQuery.matches?'dark':'light'),accent:'#3a6352'};}
function localGet(key){try{return JSON.parse(localStorage.getItem('wallpap.play.'+key));}catch{return null;}}
function localSet(key,value){localStorage.setItem('wallpap.play.'+key,JSON.stringify(value));}
function send(op,args={}){if(!LW.isHost){if(op==='fetchFeed'){const fixture=LW.virtual&&window.PlayFixtures?.feeds?.[args.id];return Promise.resolve(fixture||{items:[],updated:null,offline:true,error:'Headlines are available in the Mac app.'});}return Promise.resolve(null);}return new Promise((resolve,reject)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);reject(Error('The host did not respond. Try again.'));},16000);pending.set(id,{resolve,reject,timer});LW.post({type:'play',op,id,...args});});}
LW.on('playReply',m=>{const p=pending.get(m.id);if(p){clearTimeout(p.timer);pending.delete(m.id);m.error?p.reject(Error(m.error)):p.resolve(m.value);}});
function tell(op,value){frame?.contentWindow?.postMessage({wallpapShell:1,op,value},'*');}
function setTheme(){if(!root)return;root.dataset.theme=theme().mode;tell('theme',theme());}
themeQuery.addEventListener('change',setTheme);
function layout(){if(!root)return;const clear=LW.layout?.clear||[0,.72],x=Math.max(0,clear[0])*innerWidth,right=Math.min(1,clear[1])*innerWidth;const panel=root.querySelector('.play-panel'),width=Math.max(1,Math.min(720,right-x-32));panel.style.width=width+'px';panel.style.left=x+(right-x-width)/2+'px';const r=panel.getBoundingClientRect();LW.playRect=[r.x,r.y,r.width,r.height];LW.pets?.setScreenOccluder('play',LW.playRect);LW.emit('playOccluder',LW.playRect);}
LW.on('layout',layout);addEventListener('resize',layout);
function header(card){root.querySelector('header').innerHTML=`${card?`<button data-back aria-label="Back to Play">${svg('back')}</button>`:''}<div class="play-title">${esc(card?.name||'Play')}<span class="play-credit">${esc(card?.credit||'A little room in your day')}</span></div><button data-close aria-label="Close Play">${svg('close')}</button>`;root.querySelector('[data-close]').onclick=requestClose;const back=root.querySelector('[data-back]');if(back)back.onclick=home;}
function summary(id){const s=localGet(id)?.summary;return s?.day===PlayCore.today()&&s.done?'Done'+(s.streak?' · '+s.streak+' day streak':''):'Ready for today';}
function tile(c){return `<button class="play-tile" data-card="${c.id}" aria-label="${esc(c.name+', '+summary(c.id))}">${svg(c.icon)}<strong>${esc(c.name)}</strong><small>${c.daily?esc(summary(c.id)):'Headlines from the source'}</small></button>`;}
async function feeds(){const results=await Promise.all((window.PlayFeeds||[]).map(f=>send('fetchFeed',{feed:f.id}).catch(e=>({items:[],offline:true,updated:null,error:e.message}))));for(const r of results)for(const item of r.items)allowedLinks.add(item.link);return {items:PlayCore.dedupe(results.flatMap(r=>r.items)),offline:results.some(r=>r.offline),updated:results.map(r=>r.updated).filter(Boolean).sort()[0]||null};}
async function home(){const token=++epoch;current=null;frame=null;allowedLinks.clear();header();const main=root.querySelector('main');main.className='';const cards=PlayCatalog.map(c=>c.manifest);const hint=!localGet('hint');if(hint){try{localSet('hint',true);}catch{}}
main.innerHTML=`${hint?'<p>Daily puzzles and headlines, right on your wallpaper</p>':''}<h2>Today</h2><div class="play-grid">${cards.filter(c=>c.daily).map(tile).join('')}</div><h2>Headlines</h2><div class="play-top"><p>Loading headlines…</p></div><h2 style="margin-top:22px">${category}</h2><div class="play-grid">${cards.filter(c=>c.category===category&&!c.daily).map(tile).join('')||'<p>Your daily puzzles are above.</p>'}</div>`;
main.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>openCard(b.dataset.card));root.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));
try{const r=await feeds();if(token!==epoch||!root)return;const box=main.querySelector('.play-top');box.replaceChildren();const note=document.createElement('p');note.textContent=r.offline?'Offline · '+(r.updated?'updated '+new Date(r.updated).toLocaleString():'no saved headlines yet'):'Latest from official feeds';box.append(note);if(!PlayFeeds.length)note.textContent='Sources are awaiting syndication permission. Your daily puzzles are ready offline.';for(const item of r.items.slice(0,5)){const b=document.createElement('button');b.className='play-headline';b.textContent=item.title;const small=document.createElement('small');small.textContent=item.source+' · '+new Date(item.published).toLocaleString();b.append(small);b.onclick=()=>send('openLink',{url:item.link}).catch(e=>{note.textContent=e.message;});box.append(b);}}catch(e){if(token===epoch)main.querySelector('.play-top').textContent=e.message;}}
async function openCard(id){const entry=PlayCatalog.find(c=>c.manifest.id===id);if(!root||!entry)return;const token=++epoch;current=entry.manifest;allowedLinks.clear();header(current);send('analytics',{event:'card_open:'+id}).catch(()=>{});const main=root.querySelector('main');main.className='card-view';main.replaceChildren();frame=document.createElement('iframe');frame.title=current.name;frame.setAttribute('sandbox','allow-scripts');frame.setAttribute('referrerpolicy','no-referrer');frame.setAttribute('allow',"camera 'none'; microphone 'none'; geolocation 'none'; clipboard-read 'none'; clipboard-write 'none'");const policy="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; form-action 'none'; base-uri 'none'";frame.srcdoc=entry.html.replace('<head>',`<head><meta http-equiv="Content-Security-Policy" content="${policy}">`);main.append(frame);setTimeout(()=>{if(token===epoch)frame?.focus();},50);}
addEventListener('message',async e=>{const m=e.data;if(!root||!frame||e.source!==frame.contentWindow||!m?.wallpapCard||!current)return;const source=e.source,token=epoch,c=current;const reply=(value,error)=>{if(token===epoch&&source===frame?.contentWindow)source.postMessage({wallpapShell:1,id:m.id,value,error},'*');};
try{const a=m.args||{};if(m.op==='ready'){tell('init',{day:PlayCore.today(),theme:theme(),pro:!!config.pro});return;}if(m.op==='close'){requestClose();return;}if(!Number.isInteger(m.id)||m.id<1)throw Error('Invalid request');let value=null;
switch(m.op){case 'load':case 'save':{if(typeof a.key!=='string'||!/^[a-zA-Z0-9_.:-]{1,80}$/.test(a.key)||['__proto__','constructor','prototype'].includes(a.key))throw Error('Invalid storage key');const all=localGet(c.id)||{};if(m.op==='load')value=all[a.key]??null;else{all[a.key]=a.value;if(JSON.stringify(all).length>65536)throw Error('Local save limit reached');localSet(c.id,all);}break;}
case 'feed':if(!c.needs.network.includes(a.id)||!PlayFeeds.some(f=>f.id===a.id))throw Error('Feed not permitted');value=await send('fetchFeed',{feed:a.id});if(token!==epoch)return;for(const item of value.items)allowedLinks.add(item.link);break;
case 'open':if(typeof a.url!=='string'||!allowedLinks.has(a.url))throw Error('Link not permitted');value=await send('openLink',{url:a.url});break;
case 'event':if(a.name!=='puzzle_complete'||!c.daily)throw Error('Event not permitted');{const key='counted.'+c.id;if(localGet(key)!==PlayCore.today()){localSet(key,PlayCore.today());await send('analytics',{event:'puzzle_complete:'+c.id});}}break;
case 'ad':value=!config.pro&&c.ads&&window.PlayAdSource?PlayAdSource.pick(c.category):null;break;
case 'adOpen':if(config.pro||!c.ads)throw Error('No ad');value=await send('houseAd',{category:c.category});break;
default:throw Error('Capability not permitted');}reply(value);
}catch(e){reply(null,e.message);}});
function requestClose(){if(LW.isHost)send('close').catch(()=>{});else close();}
function close(){if(!root||closing)return;closing=true;epoch++;clearTimeout(dayTimer);root.classList.add('closing');LW.playRect=null;LW.pets?.setScreenOccluder('play',null);LW.emit('playOccluder',null);setTimeout(()=>{root?.remove();root=null;frame=null;current=null;closing=false;LW.playOpen=false;if(!LW.isHost)__lw('focus',previousFocus);},260);}
async function open(options){config=options||{};await loaded;if(!config.open)return close();if(root){setTheme();return;}previousFocus=LW.focused;LW.playOpen=true;__lw('focus',true);root=document.createElement('div');root.id='wallpap-play';root.dataset.reduce=String(!!config.reduceMotion);root.innerHTML='<section class="play-panel" role="dialog" aria-modal="true" aria-label="Play"><header></header><div class="play-body"><nav aria-label="Play categories"></nav><main></main></div></section>';document.body.append(root);for(const c of ['Puzzles','News']){const b=document.createElement('button');b.dataset.category=c;b.innerHTML=svg(c==='News'?'news':'puzzle')+c+'<small>'+PlayCatalog.filter(x=>x.manifest.category===c).length+'</small>';b.onclick=()=>{category=c;home();};root.querySelector('nav').append(b);}root.addEventListener('pointerdown',e=>{e.stopPropagation();if(e.target===root)requestClose();});for(const event of ['pointermove','pointerup','click','keydown'])root.addEventListener(event,e=>e.stopPropagation());root.addEventListener('keydown',e=>{if(e.key==='Escape')requestClose();if(e.key==='Tab'&&!frame){const a=[...root.querySelectorAll('button')],first=a[0],last=a.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});setTheme();layout();home();root.querySelector('[data-close]').focus();const midnight=new Date();midnight.setHours(24,0,0,30);dayTimer=setTimeout(()=>{if(root){const id=current?.id;id?openCard(id):home();}},midnight-Date.now());}
LW.on('play',open);window.PlayShell={open,close,openCard,home,layout,get state(){return {open:!!root,card:current?.id,pro:!!config.pro,rect:LW.playRect};}};
if(LW._playPending){const p=LW._playPending;LW._playPending=null;open(p);}
})();
