#!/usr/bin/env python3
"""Cut generated two-row dog masters; register jumps and plant 3/4 walks at .55 slope.
Originals are immutable. Uses the same alpha/chroma extraction and planting as cats.
"""
import json,subprocess,sys
from pathlib import Path
import numpy as np
from scipy import ndimage as nd
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[2];BASE=Path(__file__).resolve().parent
for dog in ['golden','corgi']:
 for gait,n,sub in [('walk',8,'cycle'),('jump',5,'t')]:
  im=Image.open(BASE/f'{dog}-{gait}.png').convert('RGBA')
  for row,view in enumerate(['f','b']):
   half=im.crop((0,row*im.height//2,im.width,(row+1)*im.height//2));a=np.array(half)
   out=ROOT/f'scenes/art/sprites/dogs/{dog}/{sub}';prefix=f'{gait}-{view}'
   if a[:,:,3].min()<255:
    lab,_=nd.label(a[:,:,3]>100);counts=np.bincount(lab.ravel());counts[0]=0
    ids=sorted(np.argsort(counts)[-n:],key=lambda k:np.where(lab==k)[1].min())
    assert min(counts[ids])>max(counts[ids])*.3
    ys=[np.where(lab==k)[0] for k in ids];top=min(y.min() for y in ys);bot=max(y.max() for y in ys)+1
    for i,k in enumerate(ids,1):
     yy,xx=np.where(lab==k);x0=max(0,xx.min()-2);x1=min(half.width,xx.max()+3)
     cut=a[top:bot,x0:x1].copy();mask=nd.binary_dilation(lab[top:bot,x0:x1]==k,iterations=2);cut[:,:,3]=np.where(mask,cut[:,:,3],0)
     Image.fromarray(cut).save(out/f'{prefix}-{i}.png')
   else:
    src=BASE/f'{dog}-{gait}-{view}.png';half.save(src)
    subprocess.run([sys.executable,str(ROOT/'art-src/cycles/cut.py'),str(src),str(out),prefix,str(n)],check=True)
# Reuse original planting algorithm with dog inputs, corrected ground heading and separate outputs.
s=(ROOT/'art-src/cycles/plant-directions.py').read_text()
s=s.replace("STRIDES=dict.fromkeys(['orange','black','grey','calico','siamese'],.5)","STRIDES=dict.fromkeys(['golden','corgi'],.5)")
s=s.replace("'cats/'","'dogs/'").replace('sprites/cats/','sprites/dogs/')
s=s.replace("np.array([1,1 if view=='f' else -1])/np.sqrt(2)","np.array([1,.55 if view=='f' else -.55])/np.hypot(1,.55)")
s=s.replace("ROOT=Path(__file__).resolve().parents[2]","ROOT=Path("+repr(str(ROOT))+")")
s=s.replace("ROOT/'art-src/cycles/directions-layout.json'","ROOT/'art-src/pets-shared/directions-layout.json'").replace("ROOT/'art-src/cycles/directions-plant-qa.json'","ROOT/'art-src/pets-shared/directions-plant-qa.json'")
# Wider deformation support keeps the inverse warp one-to-one on long golden legs.
s=s.replace('.40*H', '.75*H')
# Golden frame 2's swinging forepaw crosses the automatic torso split. Select the
# actual separate rear/front foot lobes, rather than both halves of the same paw.
s=s.replace('for a,(_,_,cx) in zip(frames,ms):','for fi,(a,(_,_,cx)) in enumerate(zip(frames,ms)):')
s=s.replace("mask=al&((xx<split) if side<0 else (xx>=split));", "split=(45 if view=='f' or side<0 else 110) if coat=='golden' and fi==1 else split;mask=al&((xx<split) if side<0 else (xx>=split));")
exec(compile(s,'dog-plant','exec'))
layout=json.loads((BASE/'directions-layout.json').read_text());jumps={}
for dog in ['golden','corgi']:
 for view in ['f','b']:
  out=ROOT/f'scenes/art/sprites/dogs/{dog}/t';cuts=[Image.open(out/f'jump-{view}-{i}.png').convert('RGBA') for i in range(1,6)]
  H=layout['dogs/'+dog]['walk-'+view]['height'];last=np.array(cuts[-1]);yy,xx=np.where(last[:,:,3]>127);factor=H*.88/(yy.max()-yy.min()+1);centers=[]
  for i,cut in enumerate(cuts,1):
   cut=cut.resize((round(cut.width*factor),round(cut.height*factor)),Image.Resampling.LANCZOS);a=np.array(cut);yy,xx=np.where(a[:,:,3]>127);top,bot=yy.min(),yy.max()
   mask=a[:,:,3]>127;mask[:round(top+(bot-top)*.3)]=False;mask[round(top+(bot-top)*.65)+1:]=False;center=np.where(mask)[1].mean()
   pad=12;c=Image.new('RGBA',(cut.width+2*pad,round(H*1.6)+2*pad));dy=c.height-pad-1-int(bot);c.paste(cut,(pad,dy));c.save(out/f'jump-{view}-{i}.png');centers.append(float(center+pad))
  jumps.setdefault('dogs/'+dog,{})['jump-'+view]={'height':H,'pad':12,'centers':centers}
(BASE/'jumps-layout.json').write_text(json.dumps(jumps,indent=2)+'\n')
# Registry has one source of truth, same module used by all eight scenes.
p=ROOT/'scenes/pet-motion.js';s=p.read_text();import re
for name,extra in [('PET_DIRECTION_LAYOUT',layout),('PET_JUMP_LAYOUT',jumps)]:
 m=re.search(r'LW\.'+name+r'=(\{.*\});',s);data=json.loads(m[1]);data.update(extra);s=s[:m.start(1)]+json.dumps(data,separators=(',',':'))+s[m.end(1):]
anchor='  // Generated by art-src/cycles/plant-directions.py:'
if "LW.PET_DIRECTION_HAS['dogs/'" not in s:s=s.replace(anchor,"  for(const id of ['golden','corgi'])LW.PET_DIRECTION_HAS['dogs/'+id]={f:['walk'],b:['walk']};\n"+anchor)
p.write_text(s)
# Compact art review at a constant runtime scale.
cv=Image.new('RGB',(1600,8*175),'#686974');d=ImageDraw.Draw(cv)
for row,(dog,gait,view) in enumerate((a,b,c) for a in ['golden','corgi'] for b in ['walk','jump'] for c in ['f','b']):
 H=layout['dogs/'+dog]['walk-'+view]['height'];d.text((5,row*175+4),dog+' '+gait+' '+view,fill='white')
 for i in range(1,9 if gait=='walk' else 6):
  im=Image.open(ROOT/f'scenes/art/sprites/dogs/{dog}/{"cycle" if gait=="walk" else "t"}/{gait}-{view}-{i}.png');im=im.crop(im.getbbox());k=115/H;im=im.resize((round(im.width*k),round(im.height*k)));cv.paste(im,((i-1)*200+20,row*175+170-im.height),im)
cv.save(ROOT/'shots/pets-shared/dog-art.jpg',quality=90)
