#!/usr/bin/env node
import {createRequire} from "node:module"; import {fileURLToPath} from "node:url"; import {dirname} from "node:path"; const require=createRequire(import.meta.url), __dirname=dirname(fileURLToPath(import.meta.url));
'use strict';const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
function validate(dir){const errors=[];let m;try{m=JSON.parse(fs.readFileSync(path.join(dir,'card.json')));}catch{return ['Missing or invalid card.json'];}const keys=['id','name','category','icon','credit','needs','daily','ads'];if(keys.some(k=>!(k in m))||Object.keys(m).some(k=>!keys.includes(k)))errors.push('Manifest fields');if(!/^([a-z0-9]+-)*[a-z0-9]+$/.test(m.id)&&m.id!=='_template')errors.push('Invalid id');if(path.basename(dir)!==m.id)errors.push('Folder/id mismatch');for(const k of ['name','credit','icon'])if(typeof m[k]!=='string'||!m[k].trim()||m[k].length>120)errors.push('Invalid '+k);if(!['puzzle','crossword','news'].includes(m.icon))errors.push('Invalid icon');if(!['Puzzles','News'].includes(m.category))errors.push('Invalid category');if(typeof m.daily!=='boolean'||typeof m.ads!=='boolean')errors.push('Boolean flags');if(!m.needs||Object.keys(m.needs).sort().join()!=='keyboard,network'||!Array.isArray(m.needs.network)||typeof m.needs.keyboard!=='boolean'||m.needs.network.some(x=>typeof x!=='string'||!/^[a-z0-9-]+$/.test(x)))errors.push('Invalid needs');
const allowedFeeds=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../scenes/play/feeds.json'))).map(f=>f.id);if(m.needs?.network?.some?.(id=>!allowedFeeds.includes(id)))errors.push('Unapproved feed');
let size=['card-sdk.js','core.js','card.css'].reduce((n,f)=>n+fs.statSync(path.resolve(__dirname,'../scenes/play',f)).size,0);function walk(d){for(const f of fs.readdirSync(d,{withFileTypes:true})){if(f.name==='data')continue;const p=path.join(d,f.name);if(f.isSymbolicLink()){errors.push('No symlinks');continue;}if(f.isDirectory())walk(p);else size+=fs.statSync(p).size;}}walk(dir);if(size>300*1024)errors.push('Bundle exceeds 300 KB');
const html=fs.existsSync(path.join(dir,'index.html'))?fs.readFileSync(path.join(dir,'index.html'),'utf8'):'';if(!html.includes('<!--CARD_SDK-->')||!html.includes('<!--CARD_STYLE-->')||!html.includes('card.ready('))errors.push('Missing SDK/style/ready');
const forbidden=[/\b(fetch|XMLHttpRequest|WebSocket|EventSource|Worker|SharedWorker|importScripts|eval|Function)\s*\(/,/\b(import\s*\(|navigator\s*[.[]|webkit\s*[.[]|localStorage|sessionStorage|indexedDB|document\s*\.\s*cookie|window\s*\.\s*open)\b/,/\b(parent|top|opener)\s*[.[]/,/<(?:iframe|object|embed|form|base|link)\b/i,/(?:src|href|action)\s*=\s*["'][^"']+/i,/url\s*\(/i,/@import\b/i,/\b(location|frames|opener)\s*[.=[(]/,/window\s*\[/,/\b(requestAnimationFrame|setInterval)\s*\(/];if(forbidden.some(r=>r.test(html)))errors.push('Sandbox-safe APIs only; no external resources or network');
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)];for(const [,code] of scripts){try{new (require('node:vm').Script)(code);}catch(e){errors.push('Script syntax: '+e.message);}}
return errors;}
if(process.argv[1]===fileURLToPath(import.meta.url)){const id=process.argv[2];if(!id||!/^[_a-z0-9-]+$/.test(id))throw Error('usage: check-card.js <id> [--static-only]');const errors=validate(path.resolve(__dirname,'../scenes/play/cards',id));if(errors.length){console.error(errors.join('\n'));process.exit(1);}console.log(id+': static gates passed');if(!process.argv.includes('--static-only')){const r=cp.spawnSync('python3',['tools/play/verify.py','--card',id,'--file'],{stdio:'inherit'});process.exit(r.status??1);}}
export {validate};
