#!/usr/bin/env node
import {createRequire} from "node:module"; import {fileURLToPath} from "node:url"; import {dirname} from "node:path"; const require=createRequire(import.meta.url), __dirname=dirname(fileURLToPath(import.meta.url));
const fs=require('node:fs'),path=require('node:path');const root=path.resolve(__dirname,'../scenes/play');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');const safe=s=>s.replace(/<\/script/gi,'<\\/script');
function pack(id){const dir='cards/'+id;const data={};if(fs.existsSync(path.join(root,dir,'data')))for(const f of fs.readdirSync(path.join(root,dir,'data')).filter(f=>f.endsWith('.json')))data[f.slice(0,-5)]=JSON.parse(read(dir+'/data/'+f));const html=read(dir+'/index.html').replace('<!--CARD_STYLE-->','<style>'+read('card.css')+'</style>').replace('<!--CARD_SDK-->','<script>'+safe(read('core.js'))+'\n'+safe(read('card-sdk.js'))+'\nconst CARD_DATA='+safe(JSON.stringify(data))+';</script>');return {manifest:JSON.parse(read(dir+'/card.json')),html};}
const cards=JSON.parse(read('catalog.json')).map(pack);fs.writeFileSync(path.join(root,'catalog.js'),'/* Generated by tools/pack-cards.js; edit card sources. */\nwindow.PlayCatalog='+JSON.stringify(cards)+';\n');
export {pack};
